### ISSUE TITLE
install sd-wrapper, connect it to resolvers and see if everything will work or not

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/graphql-server#145]
0) setup project locally **Done**
1) install sd-wrapper. our module https://github.com/GroceriStar/sd#quick-start **Done**
2) comment previous versions and use a new version here: https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js
as we make it in smart way previously, all methods located in one file, instead of checking all files
3) run this server, run tests - does it work? nothing crashing? it's strange :)

**Comment by atherdon** [comment]
you actually can start to setup this server locally. i think all will be pushed during that time

**Comment by atherdon** [comment]
Our goal will be to make this part: https://github.com/GroceriStar/sd/issues/294#issuecomment-493241485

**Comment by Edebo** [comment]
at issue#294 i already installed sd-wrapper locally and uncommented the moved functions in the https://github.com/GroceriStar/sd/tree/master/generator/projects/GraphQL/test.

step 2 in this issue# 145 isnt clear to me.i dont understand how it comes to picture

**Comment by atherdon** [comment]
emm. confused.
sd-wrapper is our small separated module, that store data.
inside sd-wrapper we have a few functions, that change structure of our data
inside sd-wrapper we have some tests, because we want to check that data is solid.

this repository(graphql-server) is a separated thing. it's an actual place and reason, why we're building sd-wrapper.

So, you need to fork this repository, install packages, install sd-wrapper and launch it locally.
tell me if this is not clear.

Example: sd-wrapper is like HDD. graphql-server is like a PC-box, that contain HDD

**Comment by Edebo** [comment]
i get the explanation of graphql-server and sd-wrapper
but i dont know if this is what you want me to do
i git clone graphql-server locally.then i npm installed sd-wrapper.then npm run test
![graphql](https://user-images.githubusercontent.com/36434800/58328718-b613fc00-7e2a-11e9-8a13-16bc96d6650d.png)

**Comment by atherdon** [comment]
looks good and test working. open pull request so i can take a look and give you more detailed answer

**Comment by Edebo** [comment]
saying no compare to make when trying to pull request

**Comment by atherdon** [comment]
hmm. as from your screenshot i see at least one change :) i mean if you install sd-wrapper - package.json should be changed.
did you also start to make an adjustments at selectors.js? you can comment that 4th line - we wouldn't need it soon(at least by my knowledge
)

**Comment by atherdon** [comment]
i think i see M near package.json - maybe you just didn't commit it :0

**Comment by atherdon** [comment]
ok, tell me if next step of this task is not clear for you

**Comment by Edebo** [comment]
yes not clear

**Comment by atherdon** [comment]
2. Comment this lines: 
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L12
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L25
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L42
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L53
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L60
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L69
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L78
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L88
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L93
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L97
https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L101

and open a PR after that.
and i'll prepare details for a next move

**Comment by atherdon** [comment]
2.5 connect files, that we have created from methods, that we copy, from fetch plugin: https://github.com/GroceriStar/sd/issues/294
as i understand - we need to have 7 files(based on 294 list)

**Comment by atherdon** [comment]
ok, right now you need to run this expressjs server and tell me if it works fine or crashes

**Comment by Edebo** [comment]
![server](https://user-images.githubusercontent.com/36434800/58362222-c52b9600-7e8c-11e9-8c77-cbd804c08aa9.png)

**Comment by Edebo** [comment]
worked fine

**Comment by atherdon** [comment]
Ok, looks like we did it! 
We have this part in "a gray area": https://github.com/GroceriStar/graphql-server/blob/master/src/data/selector.js#L88-L103 but i think we need to talk with Vadim about it, because i'm not sure if our sd-wrapper has that functions moved yet.

**Comment by atherdon** [comment]
Le'ts close it and i'll check the next task for you

**Comment by Edebo** [comment]
ok.have seen the functions.i will wait for the decision.yes boss
