### ISSUE TITLE
getItems method is missing in the fetch

### ISSUE THREAD

**Issue by nadaa** [GroceriStar/graphql-server#23]

**Comment by nadaa** [comment]
getItems, getFavorites, getUserGroceories

**Comment by atherdon** [comment]
sure. we didn't finish it. when you add samples to `data` folder - it'll save us time. But at this moment I focused on GL, Dep, Ingredient types...

**Comment by atherdon** [comment]
at this moment of time we only finished methods related to departments. When I'll receive an update from Vadim I'll pull changes to this repo and add new methods into selectors.js

**Comment by nadaa** [comment]
@atherdon, ya, data is important for testing. Still, I have problems in understanding the relationship between types.
